from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome(r"C:\Users\Purnima Sah\PycharmProjects\firstseleniumtest\Driver\chromedriver.exe")
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("http://travelerp.braindigit.com/")
print(driver.title)
print(driver.current_url)
email_ele = driver.find_element_by_name("Email")
pass_ele = driver.find_element_by_name("Password")
email_ele.send_keys("sgodar34@yopmail.com")
pass_ele.send_keys("000000")
driver.find_element_by_tag_name("button").click()
Business=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul/li[4]/a").click()
Managecharges=driver.find_element_by_xpath("/html/body/div/div[1]/div/ul/li[4]/ul/li[3]/a").click()
#for Edit of charges rules
Addnew=driver.find_element_by_xpath("/html/body/div/div[2]/div/div[5]/div[1]/div/a").click()
RuleTitle=driver.find_element_by_xpath("/html/body/div/div[2]/div/div[5]/div/div/div/div[2]/form/div[2]/div[2]/div[1]/div/div[2]/input").send_keys("New year charge")
ChargeType=driver.find_element_by_id("select2-ChargeTypeID-container").click()
Product=driver.find_element_by_xpath("/html/body/div/div[2]/div/div[5]/div/div/div/div[2]/form/div[2]/div[2]/div[3]/div/div[2]/span[1]/span[1]/span/span[1]").click()
Check=driver.find_element_by_xpath("/html/body/div/div[2]/div/div[5]/div/div/div/div[2]/form/div[2]/div[2]/div[4]/div/div[2]/label/text()").click()