from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome(r"C:\Users\Purnima Sah\PycharmProjects\firstseleniumtest\Driver\chromedriver.exe")
driver.get("http://travelerp.braindigit.com/")
print(driver.title)
print(driver.current_url)
email_ele =driver.find_element_by_name("Email")
pass_ele =driver.find_element_by_name("Password")
email_ele.send_keys("sgodar34@yopmail.com")
pass_ele.send_keys("000000")
driver.find_element_by_tag_name("button").click()
Flight=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul/li[2]").click()
Domestic= driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul/li[2]/ul/li[2]").click()
Radiobutton =driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[1]/form/div/div/div/div/div[2]/div[1]/div[1]").click()
From = driver.find_element_by_id("txtSrhFromLocation").click()
forselection=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[1]/form/div/div/div/div/div[2]/div[2]/div[1]/div[1]/div[2]").click()
To = driver.find_element_by_name("Destination").click()
Toselectthelocation=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[1]/form/div/div/div/div/div[2]/div[2]/div[1]/div[3]/div[3]/ul/li[5]").click()
Department=driver.find_element_by_id("txtDepartureDate").click()
Depatmentdate=driver.find_element_by_xpath("/html/body/div[4]/table/tbody/tr[2]/td[3]").click()
# Return=driver.find_element_by_class_name("sbFieldset sfCol_20 tsfCol_50 msfCol_50 ret").click()
Returndate=driver.find_element_by_xpath("/html/body/div[4]/table/tbody/tr[2]/td[3]").click()
passenger=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[1]/form/div/div/div/div/div[2]/div[2]/div[2]/div[1]/div[2]").click()
adult=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[1]/form/div/div/div/div/div[2]/div[2]/div[2]/div[1]/div[3]/div/div/div[3]/div/div[1]/div[2]/button[2]").click()
#baby=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[1]/form/div/div/div/div/div[2]/div[2]/div[2]/div[1]/div[3]/div/div/div[3]/div/div[2]/div[2]/button[2]").click().click()
Nationality=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[1]/form/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div[2]").click()
search=driver.find_element_by_id("btnSerchFlight1").click()
Filterresult=driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[5]/div[2]/form/div[1]/div[1]/div").click()